# /* wallust template - colors-hyprland */ 

$background = rgb(000000)
$foreground = rgb(FDF9F2)
$color0 = rgb(000000)
$color1 = rgb(2B2C29)
$color2 = rgb(554F46)
$color3 = rgb(745F4E)
$color4 = rgb(867666)
$color5 = rgb(8C7B6A)
$color6 = rgb(BBB3A4)
$color7 = rgb(F4EEE4)
$color8 = rgb(AAA7A0)
$color9 = rgb(393B37)
$color10 = rgb(72695D)
$color11 = rgb(9B7F68)
$color12 = rgb(B39D89)
$color13 = rgb(BBA48E)
$color14 = rgb(F9EEDA)
$color15 = rgb(F4EEE4)
