# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Environment variables. See https://wiki.hyprland.org/Configuring/Environment-variables/

# Set your default editor in ~/.config/hypr/UserConfigs/01-UserDefaults.conf

### QT ###
env = QT_QPA_PLATFORMTHEME,gtk3

### XWayland scale fix ###
# Set same value as scaling in monitors.conf (1 = 100%, 1.5 = 150%)
# See https://wiki.hyprland.org/Configuring/XWayland/
# env = GDK_SCALE,1
# env = QT_SCALE_FACTOR,1

### GPU (Mesa / AMD) ###
# Swap for nvidia-specific vars if needed — see https://wiki.hyprland.org/Nvidia/
env = __GLX_VENDOR_LIBRARY_NAME,mesa
env = GBM_BACKEND,drm

### Input Method (fcitx5) ###
# env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = GLFW_IM_MODULE,ibus
env = INPUT_METHOD,fcitx
env = IMSETTINGS_MODULE,fcitx
env = SDL_IM_MODULE,fcitx

### Mouse Cursor ###
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Ice
