# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = fcitx5                 # input method
exec-once = vesktop --start-minimized --enable-features=UseOzonePlatform --ozone-platform-hint=wayland --enable-wayland-ime  # wayland + IME support
exec-once = remmina -i             # remote desktop in systray
# exec-once = bottles-cli run -p Line -b 'Line' -- %u
exec-once = tailscale systray      # https://tailscale.com/kb/1597/linux-systray
exec-once = qs -c noctalia-shell   # quickshell bar
