# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = fcitx5 
exec-once = discord --start-minimized --enable-features=UseOzonePlatform --ozone-platform-hint=wayland --enable-wayland-ime 
exec-once = remmina -i 
# exec-once = bottles-cli run -p Line -b 'Line' -- %u 
# https://tailscale.com/kb/1597/linux-systray
exec-once = tailscale systray 
exec-once = qs -c noctalia-shell
