# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# Notion
windowrulev2 = workspace 10, class:^([Nn]otion)$

# Line
windowrulev2 = tag +line_main_window, class:^(line.exe)$, title:^(LINE)$
windowrulev2 = tag +line_sub_window, class:^(line.exe)$, title:^$
windowrulev2 = tag +line_explorer, class:^(explorer.exe)$

windowrulev2 = workspace 9, float, tag:line_main_window*
windowrulev2 = workspace 9, float, tag:line_sub_window*
windowrulev2 = workspace 9, float, tag:line_explorer*
