# if use mirror, set higher refresh rate monitor follow the lower one
monitor = HDMI-A-1, 1920x1080@100.0, 0x0, 1.0
monitor = eDP-1, 1920x1080@144.0, 0x0, 1.0, mirror, HDMI-A-1
monitor = vnc, preferred, 0x0, 1.0
# monitor = eDP-1, 1920x1080@144.0, 0x0, 1.0
