# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDF9F2
background         #000000
cursor             #B7B1A8

active_tab_foreground     #000000
active_tab_background     #FDF9F2
inactive_tab_foreground   #FDF9F2
inactive_tab_background   #000000

active_border_color   #FDF9F2
inactive_border_color #000000
bell_border_color     #2B2C29

color0      #000000
color1		#2B2C29
color2		#554F46
color3		#745F4E
color4		#867666
color5		#8C7B6A
color6		#BBB3A4
color7		#F4EEE4
color8		#AAA7A0
color9		#393B37
color10		#72695D
color11		#9B7F68
color12		#B39D89
color13		#BBA48E
color14		#F9EEDA
color15		#F4EEE4
