#!/usr/bin/env bash
# Apply noctalia's Material Design color scheme to noctalia-shell and rofi.
# Run this after changing your theme in noctalia's settings to sync colors.
# Note: the next wallpaper change will restore wallust-generated colors.

set -euo pipefail

NOCTALIA_COLORS="$HOME/.config/noctalia/colors.json"
NOCTALIA_WALLPAPERS="$HOME/.cache/noctalia/wallpapers.json"
QML_COLOR="$HOME/.config/quickshell/qml_color.json"
ROFI_COLORS="$HOME/.config/rofi/wallust/colors-rofi.rasi"
WALLPAPER_EFFECTS="$HOME/.config/hypr/wallpaper-effects"

if [[ ! -f "$NOCTALIA_COLORS" ]]; then
  notify-send -u critical "NoctaliaTheme" "$NOCTALIA_COLORS not found" 2>/dev/null || true
  exit 1
fi

# Read a single Material Design token from noctalia/colors.json
mc() { jq -r ".$1" "$NOCTALIA_COLORS"; }

mSurface=$(mc mSurface)
mSurfaceVariant=$(mc mSurfaceVariant)
mOnSurface=$(mc mOnSurface)
mOnSurfaceVariant=$(mc mOnSurfaceVariant)
mPrimary=$(mc mPrimary)
mSecondary=$(mc mSecondary)
mTertiary=$(mc mTertiary)
mError=$(mc mError)
mOnPrimary=$(mc mOnPrimary)
mOnSecondary=$(mc mOnSecondary)
mOutline=$(mc mOutline)
mShadow=$(mc mShadow)

# --- noctalia-shell (quickshell) ---
cat > "$QML_COLOR" << EOF
{
    "windowBackground": "$mSurface",
    "primaryText": "$mOnSurface",
    "layerBackground1": "$mPrimary",
    "layerBackground2": "$mSurfaceVariant",
    "layerBackground3": "$mShadow",
    "surfaceText": "$mOnSurface",
    "secondaryText": "$mOnSurfaceVariant",
    "borderPrimary": "$mPrimary",
    "shadowColor": "$mShadow",
    "accentPrimary": "$mPrimary",
    "accentSecondary": "$mSecondary",
    "selectionBackground": "$mPrimary",
    "accentPrimaryText": "$mOnPrimary",
    "selectionText": "$mOnPrimary",
    "borderSecondary": "$mOutline"
}
EOF

# --- rofi ---
cat > "$ROFI_COLORS" << EOF
/* noctalia Material Design theme — generated by noctalia-theme.sh */

* {
active-background: $mPrimary;
active-foreground: $mOnPrimary;
normal-background: $mSurface;
normal-foreground: $mOnSurface;
urgent-background: $mError;
urgent-foreground: $mOnPrimary;

alternate-active-background: $mSurfaceVariant;
alternate-active-foreground: $mOnSurface;
alternate-normal-background: $mSurface;
alternate-normal-foreground: $mOnSurface;
alternate-urgent-background: $mSurface;
alternate-urgent-foreground: $mOnSurface;

selected-active-background: $mPrimary;
selected-active-foreground: $mOnPrimary;
selected-normal-background: $mPrimary;
selected-normal-foreground: $mOnPrimary;
selected-urgent-background: $mSurfaceVariant;
selected-urgent-foreground: $mOnPrimary;

background-color: $mSurface;
background: rgba(0,0,0,0.85);
foreground: $mOnSurface;
border-color: $mPrimary;

color0: $mSurface;
color1: $mShadow;
color2: $mSurfaceVariant;
color3: $mOutline;
color4: $mSurfaceVariant;
color5: $mOutline;
color6: $mSurfaceVariant;
color7: $mPrimary;
color8: $mSurfaceVariant;
color9: $mShadow;
color10: $mOutline;
color11: $mSecondary;
color12: $mPrimary;
color13: $mError;
color14: $mTertiary;
color15: $mOnSurface;
}
EOF

notify-send "Noctalia Theme" "Applied Material Design colors to rofi and noctalia-shell." 2>/dev/null || true

# --- wallpaper-effects sync ---
if [[ -f "$NOCTALIA_WALLPAPERS" ]]; then
  current_wallpaper=$(jq -r '.wallpapers[""] // .wallpapers["HDMI-A-1"] // ""' "$NOCTALIA_WALLPAPERS")
  if [[ -n "$current_wallpaper" && -f "$current_wallpaper" ]]; then
    mkdir -p "$WALLPAPER_EFFECTS"
    cp "$current_wallpaper" "$WALLPAPER_EFFECTS/.wallpaper_current"
    magick "$current_wallpaper" \
      -blur 0x18 \
      -fill "$mSurface" -colorize 30 \
      -quality 90 \
      "$WALLPAPER_EFFECTS/.wallpaper_modified"
  fi
fi
